### PR TITLE
Feat/mean dist

### PR DESCRIPTION
**Pull request by oxygen-TW**
- [ADD] Add _MeanDist()_ to get the mean value of k nearest neighbors

I didn't inherit from NFacilities because if I do so, I have to override too many functions.

### CODE REVIEW

**Review by AbnerTeng — COMMENTED** [review]
@oxygen-TW Please check the command, thanks! ( *｀ω´)

**Comment by AbnerTeng** [comment]
@oxygen-TW After this branch is merged, is the file `building_dist.py` necessary?

**Comment by oxygen-TW** [comment]
Nope

**Comment by AbnerTeng** [comment]
Got it, tks!

**Pull request merged**
